# Generated by Django 2.1.3 on 2018-11-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без заголовка', max_length=200)),
                ('text', models.TextField(default='', max_length=1000)),
                ('likes', models.IntegerField(default=0)),
                ('photo', models.URLField(default='https://static.fotopoisk.com.ua/media/blog/d51737c4-dbb6-4dd5-a14d-539a22598868.jpg', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_reg',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('man', 'Мужской'), ('woman', 'Женский')], default=('man', 'Мужской'), max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(default='https://cleverpoint.pro/wp-content/uploads/2018/01/no_image.jpg', max_length=50),
        ),
        migrations.AddField(
            model_name='pin',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.User'),
        ),
    ]
