# Generated by Django 2.1.3 on 2018-11-23 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20181123_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'verbose_name': 'Пин', 'verbose_name_plural': 'Пины'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='pin',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.User', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='photo',
            field=models.URLField(default='https://static.fotopoisk.com.ua/media/blog/d51737c4-dbb6-4dd5-a14d-539a22598868.jpg', max_length=100, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='text',
            field=models.TextField(default='', max_length=1000, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='title',
            field=models.CharField(default='Без заголовка', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_reg',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('man', 'Мужской'), ('woman', 'Женский')], default=('man', 'Мужской'), max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=100, null=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(default='https://cleverpoint.pro/wp-content/uploads/2018/01/no_image.jpg', max_length=100, verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
